services:
  db:
    image: postgres:latest
    ports:
      - 5431:5432
    environment:
      - POSTGRES_DB=fedbase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
