import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@repo/ui/ui.css";
import "./globals.css";

const interSans = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interSans.className}  antialiased`}>{children}</body>
    </html>
  );
}
